server:
  port: 3001
spring:
  application:
    name: PRODUCT-SERVICE
  data:
    mongodb:
      database: productsDB
      port: 27017
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default:zone: http://localhost:8761/eureka
    instance:
      hostname: localhost